---
title: "Forecasting_intro"
author: "Sri Seshadri"
date: "4/6/2018"
output: 
  html_document:
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
```

### Bring in data and visualize

```{r}
SANM <- read.csv(file = "SANM.csv")
SANM  %<>% dplyr::mutate(Date = as.Date(Date)) %>% 
           dplyr::mutate(Datenum = as.numeric(Date))

ggplot(data = SANM, mapping = aes(x = Date, y = Close)) + geom_point()  + geom_smooth(mapping = aes(x = Date, y = Close),method = "loess")

ggplot(data = SANM, mapping = aes(x = Date, y = Close)) + geom_point()  + geom_smooth(mapping = aes(x = Date, y = Close),method = "lm")
```


 last datenum was 17623

 New data to predict, next 30 days
 
```{r}
Newdata = data.frame(Datenum = seq(17624,by = 1,length.out = 30))

```

Loess smoother is better... let's fit loess 

```{r}
loess.mdl <- loess(Close ~ Datenum, data = SANM,control = loess.control(surface = "direct"))
# fit the model to the new data
Newdata$Close <- predict(loess.mdl,newdata = Newdata)
```


Prepare data for plotting

```{r}
Stocks <- SANM %>% dplyr::select(Datenum,Close)
Stocks <- rbind.data.frame(Stocks, Newdata)
Stocks <- Stocks %>% dplyr::mutate(Date = lubridate::as_date(Datenum))

Stocks <- Stocks %>% dplyr::mutate(Predicted = c(rep("Actual",503),rep("Predicted",30)))

ggplot(data = Stocks, mapping = aes(x = Date, y = Close, color = Predicted)) + geom_point() + geom_smooth(method = "loess") + ggtitle("Stock price of SANMINA CORP (SANM)")
```

